### ISSUE TITLE
Possible error in GenerationalIndexArray remove method.

### ISSUE THREAD

**Issue by andrewtron3000** [kyren/simplecs#2]
Hello, I think there might be an error on line 185 of src/generational_index.rs (commit id 977090a).  The comparison is checking equality of the value of `e.generation` against itself.

**Comment by kyren** [comment]
That is indeed an error!  Thanks!

Just so you know, this project was adapted from another larger project, and there was an error in translation.

The purpose of this project was just to demonstrate a particular "querying" API style, not really for serious use.  However, there's no reason to leave such a bug, so thanks for that.

I think I need to add a README that warns people away for using this for anything other than educational use and API inspiration, though.

**Comment by andrewtron3000** [comment]
You're welcome.  After watching your RustConf 2018 talk, I came here to learn more.  I did find this project to be helpful.
